# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b706498e2086a17f4309753c5de3896e8438366a07161cbe26b546378095ec7966d4bb0537102d15ca6418406269eb8e847514a83b1c21ac072c2fb40354dd57

test:
  secret_key_base: 4e1ea3abea9714be9b6de4fd0dd88a568b3eb9d0cdfb03f9e1f814e8cd991149e4af7d57ec2ec90e94ab9c98c09ff9c42c7f980fa8b6f8571c9e384f6e7cc92f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
